### ISSUE TITLE
Not unicode-friendly

### ISSUE THREAD

**Issue by Lemmmy** [fish-face/quasselgrep#9]
I'm in a lot of non-English IRC channels, and quasselgrep crashes when printing lines containing non-ASCII characters.

```
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/lem/quasselgrep/quasselgrep/__main__.py", line 228, in <module>
    main()
  File "/home/lem/quasselgrep/quasselgrep/__main__.py", line 225, in main
    program = QuasselGrep()
  File "/home/lem/quasselgrep/quasselgrep/__main__.py", line 60, in __init__
    for res in results: print(query.format(res))
UnicodeEncodeError: 'ascii' codec can't encode character '\u20ac' in position 62: ordinal not in range(128)
```

**Comment by Lemmmy** [comment]
LANG was not defined.
